source "https://rubygems.org"

gem "rails", "~> 8.1.2"
gem "falcon"
gem "propshaft"
gem "pg"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "bootsnap", require: false

gem "async-websocket"
gem "async-http"

# The engine under development
gem "open_resource", path: ".."

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
end
